### ISSUE TITLE
client/server settings in wrong files

### ISSUE THREAD

**Issue by eikenb** [linrock/ssh-tunnels#2]
In the "Reliable SSH Tunnels" section you have the files for the client and server settings backwards.

The `ClientAliveCountMax` and `ClientAliveInterval` are listed as going in /etc/ssh/ssh_config (client's config), but they belong in `/etc/ssh/sshd_config` (servers config). They set how the server manages the client connections. Reference: https://man.openbsd.org/sshd_config.5#ClientAliveCountMax

The corresponding `ServerAliveInterval` and `ServerAliveCountMax` belong in the client's config, `/etc/ssh/ssh_config`, as they are setting properties on the client's connection to the server.
Reference: https://man.openbsd.org/ssh_config.5#ServerAliveCountMax

**Comment by linrock** [comment]
thanks for reporting! i've updated the site with the fixed settings
